name: motaperp_tctsolutions
description: A new Flutter project.

publish_to:
version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons:
  fluttertoast:
  mask_text_input_formatter:
  shared_preferences:
  http:
  focused_menu:
  path_provider:
  flutter_launcher_icons:
  flutter_bloc:
  change_app_package_name:
  barcode_scan2:
  intl:
  dropdown_search: 3.0.1
  flutter_datetime_picker:
  turkish:
  provider:
  connectivity_plus:
  easy_localization: ^3.0.0
  email_validator: ^2.0.1
  carousel_slider:
  qr_flutter:
  url_launcher:
  intl_phone_number_input: ^0.7.0+2
  percent_indicator:
  firebase_core:
  firebase_messaging:
  flutter_local_notifications:



flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "asset/icon/logo3.png"

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  fonts:
    - family: Bozon
      fonts:
        - asset: asset/font/bozon/Bozon-Black.otf
        - asset: asset/font/bozon/Bozon-Regular.otf
  uses-material-design: true
  assets:
     - asset/language/
     - asset/icon/

